### ISSUE TITLE
Review HotKeys

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#183]

**Comment by Entkenntnis** [comment]
Some investigations: Focus on div in generally working (e.g. image plugin), but react-hotkeys is not able to match ArrowUp/ArrowDown events anymore on this div (or textarea, or input or anything). 

Seems to be an issue with react-hotkeys itself: https://github.com/greena13/react-hotkeys/issues/209

Can be worked around with #230 - but we may encounter this bug in further situations.

**Comment by Knorrke** [comment]
#230 trys to actually focus a DOM element, wenn a plugin receives focus, which helps reducing these HotKeys problems. Currently the focus will be lost and `document.activeElement` references `body`... So the Hotkeys component won't do anything, because no child has focus.

So #230 is pretty unrelated to the upstream issue you linked.

**Comment by Entkenntnis** [comment]
The original bug is not documented and has probably changed in the 4 years. The disccusion is probably outdated.

A new issue with more specific things that doesn't work would be appreaciated.
