### ISSUE TITLE
Using plugins with independent microservice backend

### ISSUE THREAD

**Issue by sr258** [edtr-io/edtr-io#322]
I'm unsure whether what I have in mind will work with the current architecture of edtr.io, so maybe someone can clarify whether this will work or not.

I want to write a custom plugin for an H5P microservice. The H5P microservice is fully independent in that it provides a REST endpoint for CRUD operations of H5P content objects. I want the edtr.io plugin to be capable of displaying and editing H5P content.

My idea is to only store the id of content objects of the H5P microservice in the document created and displayed by edtr.io. The SPA H5P player and editor of the plugin receive the content id from the document (basically a reference) and then load the actual H5P content via a REST endpoint and displays the UI. While this will be simple enough for the player, I wonder how this can work for the editor. The POST / PATCH endpoint of the H5P microservice must be called in order to save H5P content. The response to the request then contains the id of the content object. This id must be stored in the edtr.io document.

Is it possible to integrate the HTTP request to the H5P microservice in edtr.io's architecture? At which point would this be done?

**Comment by inyono** [comment]
Hey, I apologize for the late response. Was out last week and needed to catch up to work stuff today.

Basically there are three options for handling state in Edtr.io:
- You embed the plugin's state directly into Edtr.io's state. This usually leads to the most "native" experience (e.g. undo/redo and other built-in features) but only makes sense if the state is manageable (e.g. not too big and serializable) and you can provide a React Form component for the plugin. I'm not too familiar with H5P, but both of these might be tricky in your case.
- On the other spectrum, you can persist the state and handle the editing somewhere externally and just save some identifier in Edtr.io's state. This is the most simplest variant but you lose some Edtr.io features. We used this approach for our GeoGebra applet where users can use geogebra.org to create/upload their applet and only need to specify the URL to the applet. We then use the API to retrieve some information about the applet. This should probably work for your use case.
- There's a third option if you want to improve on the UX in the second option: you can provide a React Form component for the plugin that communicates with the API of your microservice. This way, the user doesn't need to use the microservice directly and can edit stuff with a (hopefully) familiar experience. Since you still lose some of Edtr.io's features, you might want to take extra care about how you handle the UX in this case. E.g. one UX challenge is to make it clear to your users that undo/redo won't work for this plugin. You could, for example, make the editing & saving process explicit:
  - When the user clicks the plugin, you open an overlay that shows the editor to create a H5P plugin.
  - When the user saves that, you maybe ask for confirmation, do the corresponding HTTP requests to save the H5P entity and then embed an identifier into the document.

Hopefully this gives you a broad overview of how you can approach this specific problem. Let me know if you have any more follow-up questions and I gladly dive deeper where necessary.

**Comment by sr258** [comment]
Thanks for your answer! No worries, it‘s not urgent.

In theory H5P would probably work with option 1, as it mostly produces and consumes JSON data. I‘m not certain whether the editor allows things like external undo/redo operations, though. I also want to avoid integrating the h5p stuff too deep on the server-side, which would be needed in such a scenario (validation of content against schemas and sanitizing user input). As H5P has its own way of uploading resources (images, videos, ...), there might also be issues with that.

I‘ve though about option 2 and would like deeper integration. So I have a few questions about option 3:

- While your suggestion would work, it creates the problem of having inconsistent states between H5P and Edtr.io‘s content. It is possible that a user saves H5P content, but then discards the Edtr.io content (e.g. by closing the browser). In this case, the content will live in the H5P microservice forever...
- Are there hook or events like beforeSave(), which the H5P React Form could subscribe to? In this case it would be possible to persist the H5P object and then modify the state in Edtr.io.
- Is there documentation on the way state is managed by Edtr.io? I‘ve found some basic information, but I haven‘t yet fully understood how state works here.

**Comment by inyono** [comment]
> * While your suggestion would work, it creates the problem of having inconsistent states between H5P and Edtr.io‘s content. It is possible that a user saves H5P content, but then discards the Edtr.io content (e.g. by closing the browser). In this case, the content will live in the H5P microservice forever...

Some approaches that would be possible here:
- Solve this via good UX, i.e. make it clear to the user that they are editing the H5P content and they actually change it after they confirmed the saving, even when they cancel the edit later. You might need something like that anyways if you intend to use the H5P content in other places, too, since you wouldn't want users to completely change the nature of the H5P content (so that it still works in the other places, too).
- Not sure if your microservice has the concept of a revision / changelog of H5P content. If so, you could save the revision identifier additionally to the H5P identifier in the Edtr.io state. If not, maybe you could create a new H5P entity for every meaningful edit (which would basically fake a changelog and make H5P content immutable). Something like this might be especially useful if you also plan to save multiple revisions of Edtr.io states (e.g. again for a changelog, like we do on serlo.org) so that reverting to an earlier Edtr.io state also reverts the applet.
- Only save the H5P content if you also save the Edtr.io state which basically leads to your next question.

> * Are there hook or events like beforeSave(), which the H5P React Form could subscribe to? In this case it would be possible to persist the H5P object and then modify the state in Edtr.io.

We don't have such a hook at the moment (we currently only allow plugins to specify how their content should be serialized but this needs to be synchronous, so no API requests). You could work around this by using a React context where the H5P React Form persists a description of the API requests that should be done when saving. And your Editor component (the component that integrates Edtr.io with your actual app and decides where to save the Edtr.io state) uses the context value when an Edtr.io document is saved to also trigger the API requests. Since this is a rather special case (and you can work around this by using React itself), I'm not sure if it makes sense to add the functionality to the core itself, but I can think about that.

> * Is there documentation on the way state is managed by Edtr.io? I‘ve found some basic information, but I haven‘t yet fully understood how state works here.

Sure, I can write something up. Our current documentation on edtr.io is rather on a high-level and doesn't really go into details yet. State management (and possibly some more information on how to integrate Edtr.io with your app which would cover the previous question a little bit) is definitely an important thing to document. Can you create an issue for that in https://github.com/edtr-io/docs/issues? You can also add questions you had about state management to the issue so I definitely cover those.
