### ISSUE TITLE
Math notations are not displayed properly

### ISSUE THREAD

**Issue by quanphan2906** [edtr-io/edtr-io#334]
The editor allows me to add math notations (with the F(x) symbol). On focus, the notations are displayed properly. However, as the mouse focus is on another line of text in the editor, the notations are replaced by their Latex forms. Below is the code hosted on CodeSandbox.

[https://codesandbox.io/s/edtr-testing-g0qdp?file=/src/App.js](url)

Not sure if this is a bug or an intentional design. If the latter is true, how can I display the math properly, as I cannot find any relevant guidance on the docs.

**Comment by inyono** [comment]
You didn't include the KaTeX stylesheet (which we don't include automatically since we don't know how you handle CSS in your app):
```tsx
// Or include the Stylesheet in a different way
import "katex/dist/katex.css";
```

So the following works (thanks for the easy repro with CodeSandbox btw):

https://codesandbox.io/s/edtr-testing-forked-us5uu

Feel free to reopen when you run into other problems.
